city_index:
    path:     /
    defaults: { _controller: "TravelBundle:City:index" }
    methods:  GET

city_show:
    path:     /{id}/show
    defaults: { _controller: "TravelBundle:City:show" }
    methods:  GET

city_new:
    path:     /new
    defaults: { _controller: "TravelBundle:City:new" }
    methods:  [GET, POST]

city_edit:
    path:     /{id}/edit
    defaults: { _controller: "TravelBundle:City:edit" }
    methods:  [GET, POST]

city_delete:
    path:     /{id}/delete
    defaults: { _controller: "TravelBundle:City:delete" }
    methods:  DELETE
