_index:
    path:     /
    defaults: { _controller: "TravelBundle:Stuff:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "TravelBundle:Stuff:show" }
    methods:  GET

_new:
    path:     /new
    defaults: { _controller: "TravelBundle:Stuff:new" }
    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "TravelBundle:Stuff:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{id}/delete
    defaults: { _controller: "TravelBundle:Stuff:delete" }
    methods:  DELETE

_priority:
    path:     /sort/{priority}
    defaults: {_controller: "TravelBundle:Stuff:priority" }
    methods:  GET
