travel_panoply:
    resource: "@TravelBundle/Controller/PanoplyController.php"
    type:     annotation

travel:
    resource: "@TravelBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
