<?php

namespace TravelBundle\Repository;

/**
 * PanoplyLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanoplyLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
