<?php

namespace TravelBundle\Repository;

/**
 * PanoplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanoplyRepository extends \Doctrine\ORM\EntityRepository
{
}
