<?php

namespace TravelBundle\Repository;

/**
 * StuffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuffRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWhere($find, $operateur)
    {
        $queryBuilder = $this->createQueryBuilder('stuff');
        $queryBuilder->where('stuff.priority '.$operateur.' :'.$find);
        return $queryBuilder->getQuery()->getResult();
    }

}
