stuff:
    resource: "@TravelBundle/Resources/config/routing/stuff.yml"
    prefix:   /

category:
    resource: "@TravelBundle/Resources/config/routing/category.yml"
    prefix:   /category

travel:
    resource: "@TravelBundle/Resources/config/routing/travel.yml"
    prefix:   /travel

city:
    resource: "@TravelBundle/Resources/config/routing/city.yml"
    prefix:   /city

travel_homepage:
    path:     /
    defaults: { _controller: TravelBundle:Default:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
